# CMake generated Testfile for 
# Source directory: /net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c
# Build directory: /autofs/unityaccount/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_ymaabout_test_dummy "./game_test_ymaabout" "dummy")
set_tests_properties(test_ymaabout_test_dummy PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;23;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_is_over "./game_test_ymaabout" "game_is_over")
set_tests_properties(test_ymaabout_test_game_is_over PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;24;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_restart "./game_test_ymaabout" "game_restart")
set_tests_properties(test_ymaabout_test_game_restart PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;25;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_play_move "./game_test_ymaabout" "game_play_move")
set_tests_properties(test_ymaabout_test_game_play_move PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;26;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_check_move "./game_test_ymaabout" "game_check_move")
set_tests_properties(test_ymaabout_test_game_check_move PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;27;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_print "./game_test_ymaabout" "game_print")
set_tests_properties(test_ymaabout_test_game_print PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;28;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_ymaabout_test_game_is_wrapping "./game_test_ymaabout" "game_is_wrapping")
set_tests_properties(test_ymaabout_test_game_is_wrapping PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;29;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_dummy "./game_test_juruch" "dummy")
set_tests_properties(test_juruch_test_dummy PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;31;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_new_empty "./game_test_juruch" "game_new_empty")
set_tests_properties(test_juruch_test_game_new_empty PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;32;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_delete "./game_test_juruch" "game_delete")
set_tests_properties(test_juruch_test_game_delete PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;33;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_set_square "./game_test_juruch" "game_set_square")
set_tests_properties(test_juruch_test_game_set_square PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;34;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_get_next_square "./game_test_juruch" "game_get_next_square")
set_tests_properties(test_juruch_test_game_get_next_square PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;35;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_default "./game_test_juruch" "game_default")
set_tests_properties(test_juruch_test_game_default PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;36;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_juruch_test_game_default_solution "./game_test_juruch" "game_default_solution")
set_tests_properties(test_juruch_test_game_default_solution PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;37;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_dummy "./game_test_argomes" "dummy")
set_tests_properties(test_argomes_test_dummy PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;39;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_has_error "./game_test_argomes" "game_has_error")
set_tests_properties(test_argomes_test_game_has_error PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;40;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_copy "./game_test_argomes" "game_copy")
set_tests_properties(test_argomes_test_game_copy PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;41;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_is_immutable "./game_test_argomes" "game_is_immutable")
set_tests_properties(test_argomes_test_game_is_immutable PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;42;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_is_empty "./game_test_argomes" "game_is_empty")
set_tests_properties(test_argomes_test_game_is_empty PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;43;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_equal "./game_test_argomes" "game_equal")
set_tests_properties(test_argomes_test_game_equal PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;44;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_get_next_number "./game_test_argomes" "game_get_next_number")
set_tests_properties(test_argomes_test_game_get_next_number PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;45;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_get_number "./game_test_argomes" "game_get_number")
set_tests_properties(test_argomes_test_game_get_number PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;46;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_new "./game_test_argomes" "game_new")
set_tests_properties(test_argomes_test_game_new PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;47;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_get_square "./game_test_argomes" "game_get_square")
set_tests_properties(test_argomes_test_game_get_square PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;48;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_new_ext "./game_test_argomes" "game_new_ext")
set_tests_properties(test_argomes_test_game_new_ext PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;49;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_new_empty_ext "./game_test_argomes" "game_new_empty_ext")
set_tests_properties(test_argomes_test_game_new_empty_ext PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;50;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_nb_rows "./game_test_argomes" "game_nb_rows")
set_tests_properties(test_argomes_test_game_nb_rows PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;51;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_nb_cols "./game_test_argomes" "game_nb_cols")
set_tests_properties(test_argomes_test_game_nb_cols PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;52;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_is_wrapping "./game_test_argomes" "game_is_wrapping")
set_tests_properties(test_argomes_test_game_is_wrapping PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;53;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_is_unique "./game_test_argomes" "game_is_unique")
set_tests_properties(test_argomes_test_game_is_unique PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;54;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_undo "./game_test_argomes" "game_undo")
set_tests_properties(test_argomes_test_game_undo PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;55;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
add_test(test_argomes_test_game_redo "./game_test_argomes" "game_redo")
set_tests_properties(test_argomes_test_game_redo PROPERTIES  _BACKTRACE_TRIPLES "/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;56;add_test;/net/cremi/ymaabout/Bureau/projet techno L2/takuzu-11c/CMakeLists.txt;0;")
